In [53]:
import numpy as np

In [54]:
class Three_Layer_Neural_Network_Commented():
    
    def __init__(self):     
        # self.synaptic_weight_0 = 2*np.random.random((3,4)) - 1 
        self.synaptic_weight_0 = np.asarray([[-0.1556352, 0.03320346, -0.13355978, 0.57232395], 
                                             [-0.09049334, 0.25541687, -0.62995156, -0.03174671], 
                                             [-0.55489966, 0.43029212, -0.77468673, -0.75519486]])
        print("self.synaptic_weight_0")
        print(self.synaptic_weight_0)
        print()
        
        # self.synaptic_weight_1 = 2*np.random.random((4,1)) - 1
        self.synaptic_weight_1 = np.array([[-0.77467824], 
                                           [-0.63463163], 
                                           [ 0.76931812], 
                                           [ 0.06303952]])
        print("self.synaptic_weight_1")
        print(self.synaptic_weight_1)
        print()
        
        
    # This is a function that "squishes"/maps a value to a value between 0 and 1
    # Used to convert numbers into probabilities and/or normalise them between 0 and 1 
    # This is the equivalent of the step function of a perceptron. 
    # This activation function returns continuous values instead of discrete like the step funcion of the perceptron
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    # Returns the derivative (slope (inclination, gradient))
    # Indicates how confident we are about the existing weight
    def __sigmoid_derivative(self, x):
        return x * (1 - x)
    
    # This training process is a trial and error process using random initialized synaptic_weights
    # These random initialized synaptic weights are updated every iteration
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):

        print('layer0 training_set_inputs')
        print(training_set_inputs)
        print()
        
        print('training_set_outputs)')
        print(training_set_outputs)
        print()
        
        debug_print_frequency = 5000
           
        for iteration in range(number_of_training_iterations):        
            
            if iteration % debug_print_frequency == 0:
                print()
                print("##### Iteration: ", iteration)
                print()
            
            # Forward propagate through layers 0, 1, and 2
            layer0 = training_set_inputs
            
            layer1_before_sigmoid = np.dot(layer0,self.synaptic_weight_0)
            if iteration % debug_print_frequency == 0:
                print("layer1_before_sigmoid")
                print(layer1_before_sigmoid)
                print()
            
            layer1 = self.__sigmoid(np.dot(layer0,self.synaptic_weight_0))
            if iteration % debug_print_frequency == 0:
                print("layer1_sigmoid")
                print(layer1)  
                print()
                
            layer2_before_sigmoid = np.dot(layer1,self.synaptic_weight_1)
            if iteration % debug_print_frequency == 0:
                print("layer2_before_sigmoid")
                print(layer2_before_sigmoid)
                print()
            
            layer2 = self.__sigmoid(np.dot(layer1,self.synaptic_weight_1))
            if iteration % debug_print_frequency == 0:
                print("layer2_sigmoid")
                print(layer2)
                print()
                               
            # Calculate error for layer 2
            layer2_error = training_set_outputs - layer2
            if iteration % debug_print_frequency == 0:
                print("layer2_error")
                print(layer2_error)
                print()
                
            sigmoid_derivative_layer2 = self.__sigmoid_derivative(layer2)
            if iteration % debug_print_frequency == 0:
                print("sigmoid_derivative_layer2")
                print(sigmoid_derivative_layer2)
                print()
            
            # Use the error to compute the gradient
            layer2_gradient = layer2_error * sigmoid_derivative_layer2
            if iteration % debug_print_frequency == 0:
                print("layer2_gradient")
                print(layer2_gradient)
                print()
                      
            synaptic_weight_1_transpose = self.synaptic_weight_1.T   
            if iteration % debug_print_frequency == 0:
                print("synaptic_weight_1_transpose")
                print(synaptic_weight_1_transpose)
                print()
            
            
            # Calculate error for layer 1
            # This error calculation uses "confidence weighted error" from layer2 to establish an error for layer1
            # To do this we simply send the error across the weights from layer2 to layer1
            # This gives what you could call a "contribuition weighted error" because we learn how much each node
            # in layer1 "contributed" to the error in layer2. This step is called BACKPROPAGATION
            # WHY IS THE layer_gradient MATRIX MULTIPLIED BY THE TRANSPOSE OF synaptic_weight_1?
                # It is an elegant solution, because it creates an implicit summation through matrix multiplication
                # https://gist.github.com/denzilc/1332063
            layer1_error = layer2_gradient.dot(self.synaptic_weight_1.T)
            if iteration % debug_print_frequency == 0:
                print("layer1_error")
                print(layer1_error)
                print()


            sigmoid_derivative_layer1 = self.__sigmoid_derivative(layer2)
            if iteration % debug_print_frequency == 0:
                print("sigmoid_derivative_layer1")
                print(sigmoid_derivative_layer1)
                print()
                
            # Use it to compute its gradient
            layer1_gradient = layer1_error * sigmoid_derivative_layer1
            if iteration % debug_print_frequency == 0:
                print("layer1_gradient")
                print(layer1_gradient)
                print()
                            
            # Update the weights using the gradients
            layer1_transpose = layer1.T  
            
            self.synaptic_weight_1 += layer1_transpose.dot(layer2_gradient)
            
            if iteration % debug_print_frequency == 0:
                print("layer1_transpose")
                print(layer1_transpose)
                print()
            
            if iteration % debug_print_frequency == 0:
                print("updated self.synaptic_weight_1")
                print(self.synaptic_weight_1)
                print()
            
            
            self.synaptic_weight_0 += layer0.T.dot(layer1_gradient)
            if iteration % debug_print_frequency == 0:
                print("updated self.synaptic_weight_0")
                print(self.synaptic_weight_0)
                print()
            
            layer0_transpose = layer0.T
            if iteration % debug_print_frequency == 0:
                print("layer0_transpose")
                print(layer0_transpose)
                print()
                
            if iteration % debug_print_frequency == 0:
                print("updated self.synaptic_weight_0")
                print(self.synaptic_weight_0)
                print()
            
            
    
    def predict(self, inputs):
        print('starting Prediction')
        print('inputs')
        print(inputs)
        print()
        
        layer1 = self.__sigmoid(np.dot(inputs,self.synaptic_weight_0))
        print('layer1')
        print(layer1)
        print()
        
        layer2 = self.__sigmoid(np.dot(layer1,self.synaptic_weight_1)) 
        print('layer2')
        print(layer2)
        print()
        
        return layer2

In [55]:
neural_network = Three_Layer_Neural_Network_Commented()
training_set_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = np.array([[0],[1], [1], [0]])
neural_network.train(training_set_inputs, training_set_outputs, 10000)

self.synaptic_weight_0
[[-0.1556352   0.03320346 -0.13355978  0.57232395]
 [-0.09049334  0.25541687 -0.62995156 -0.03174671]
 [-0.55489966  0.43029212 -0.77468673 -0.75519486]]

self.synaptic_weight_1
[[-0.77467824]
 [-0.63463163]
 [ 0.76931812]
 [ 0.06303952]]

layer0 training_set_inputs
[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]

training_set_outputs)
[[0]
 [1]
 [1]
 [0]]


##### Iteration:  0

layer1_before_sigmoid
[[-0.55489966  0.43029212 -0.77468673 -0.75519486]
 [-0.8010282   0.71891245 -1.53819807 -0.21461762]
 [-0.71053486  0.46349558 -0.90824651 -0.18287091]
 [-0.645393    0.68570899 -1.40463829 -0.78694157]]

layer1_sigmoid
[[ 0.3647284   0.60594342  0.31546615  0.31969042]
 [ 0.30980562  0.67236749  0.17679738  0.4465506 ]
 [ 0.32948067  0.6138431   0.28735879  0.45440925]
 [ 0.34402846  0.66501169  0.19708112  0.31282575]]

layer2_before_sigmoid
[[-0.40425106]
 [-0.50254159]
 [-0.39508968]
 [-0.51721036]]

layer2_sigmoid
[[ 0.40029141]
 [ 0.37694357]
 [ 0.40249267]
 [ 0.37350478

In [66]:
print("Considering new situation [1, 0, 0] -> ?: ")
print(neural_network.predict(np.array([1, 0, 1])))

Considering new situation [1, 0, 0] -> ?: 
starting Prediction
inputs
[1 0 1]
layer1
[ 0.11263794  0.13664507  0.87299222  0.87921293]
layer2
[ 0.99595915]
[ 0.99595915]


References:

https://medium.com/technology-invention-and-more/how-to-build-a-simple-neural-network-in-9-lines-of-python-code-cc8f23647ca1

http://iamtrask.github.io/2015/07/12/basic-python-network/